import { GoogleGenAI, Type } from "@google/genai";
import { TripDetails, QuotationItem, GroundServiceRate } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY || "" });

export const chatWithAI = async (
  messages: { role: 'user' | 'assistant'; content: string }[],
  availableRates: GroundServiceRate[]
): Promise<{ text: string; quotation?: { details: TripDetails; items: QuotationItem[]; draftText?: string } }> => {
  const model = "gemini-3.1-pro-preview";
  
  // Provide the full rate sheet to the AI so it can use accurate pricing
  const ratesData = availableRates.map(r => ({
    segment: r.segment,
    paxRange: r.paxRange,
    minPax: r.minPax,
    maxPax: r.maxPax,
    rate: r.rate,
    currency: r.currency
  }));

  const contents = messages.map(m => ({
    role: m.role === 'user' ? 'user' : 'model' as const,
    parts: [{ text: m.content }]
  }));

  const response = await ai.models.generateContent({
    model,
    contents,
    config: {
      systemInstruction: `
        You are a professional travel agency assistant. Your goal is to help users build travel quotations.
        
        AVAILABLE RATES DATABASE (Strictly use these rates, DO NOT assume or invent rates):
        ${JSON.stringify(ratesData, null, 2)}
        
        Guidelines:
        1. Be conversational and helpful, like ChatGPT.
        2. If the user provides trip details (client name, trip name, pax, dates, segments), you should prepare a quotation.
        3. When you have enough information to generate a quotation, you MUST include a special JSON block at the end of your response wrapped in <QUOTATION_DATA> tags.
        4. The JSON block must follow this schema:
           {
             "details": {
               "clientName": string,
               "tripName": string,
               "paxCount": number,
               "startDate": "YYYY-MM-DD",
               "endDate": "YYYY-MM-DD",
               "segments": string[],
               "additionalNotes": string
             },
             "items": [
               { "segment": string, "description": string, "quantity": number, "unitPrice": number, "totalPrice": number }
             ],
             "draftText": string (a professional markdown draft of the quotation)
           }
        5. CRITICAL: For the items, use the exact segment names and unit prices from the AVAILABLE RATES DATABASE. Do not invent prices.
        6. CRITICAL: If the user revises the quotation (e.g., changes pax count), you MUST recalculate using the accurate rates from the database. Do not drop rates or items unless explicitly asked.
        7. CRITICAL: Keep the drafting pattern consistent. The 'draftText' must be a highly professional, beautifully formatted Markdown email/document. Use the following structure:
           
           # Quotation: [Trip Name]
           **Prepared for:** [Client Name] | **Pax:** [Pax Count] | **Dates:** [Start] to [End]
           
           ---
           
           Dear [Client Name],
           
           [Warm, engaging opening paragraph summarizing the trip]
           
           ### 🗺️ Itinerary Overview
           [Brief bulleted list or summary of the segments]
           
           ### 💰 Investment Breakdown
           [A clean markdown table showing Segment, Description, Quantity, Unit Price, and Total Price]
           
           **Total Investment: [Total Amount]**
           
           ### 📌 Important Notes & Inclusions
           [Any additional notes, terms, or inclusions]
           
           [Professional closing]
           
           ---
           *Generated by TravelAI*
        8. If information is missing, ask the user for it politely.
        9. Current Date: ${new Date().toISOString().split('T')[0]}
      `,
    },
  });

  const text = response.text;
  let quotation;

  const match = text.match(/<QUOTATION_DATA>([\s\S]*?)<\/QUOTATION_DATA>/);
  if (match) {
    try {
      quotation = JSON.parse(match[1]);
    } catch (e) {
      console.error("Failed to parse quotation data from AI response", e);
    }
  }

  return { 
    text: text.replace(/<QUOTATION_DATA>[\s\S]*?<\/QUOTATION_DATA>/, "").trim(), 
    quotation 
  };
};

export async function draftQuotationText(details: TripDetails, items: QuotationItem[]): Promise<string> {
  const itemsText = items.map(item => `- ${item.segment}: ${item.description} (${item.quantity} x ${item.unitPrice}) = ${item.totalPrice}`).join("\n");
  
  const prompt = `
    You are a professional travel consultant. Draft a professional and welcoming travel quotation for a client.
    
    Client Name: ${details.clientName}
    Trip Name: ${details.tripName}
    Pax Count: ${details.paxCount}
    Dates: ${details.startDate} to ${details.endDate}
    Additional Notes: ${details.additionalNotes}
    
    Proposed Itinerary/Items:
    ${itemsText}
    
    Total Amount: ${items.reduce((sum, item) => sum + item.totalPrice, 0)}
    
    Please write a highly professional, beautifully formatted Markdown email/document. Use the following exact structure:
    
    # Quotation: ${details.tripName}
    **Prepared for:** ${details.clientName} | **Pax:** ${details.paxCount} | **Dates:** ${details.startDate} to ${details.endDate}
    
    ---
    
    Dear ${details.clientName},
    
    [Warm, engaging opening paragraph summarizing the trip]
    
    ### 🗺️ Itinerary Overview
    [Brief bulleted list or summary of the segments]
    
    ### 💰 Investment Breakdown
    [A clean markdown table showing Segment, Description, Quantity, Unit Price, and Total Price based on the items below]
    
    **Total Investment: ${items.reduce((sum, item) => sum + item.totalPrice, 0)}**
    
    ### 📌 Important Notes & Inclusions
    ${details.additionalNotes ? details.additionalNotes : '[Standard terms and inclusions]'}
    
    [Professional closing]
    
    ---
    *Generated by TravelAI*
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
    });
    return response.text || "Failed to generate draft.";
  } catch (error: any) {
    console.error("Gemini Error:", error);
    const errorString = error?.toString() || "";
    if (error?.status === 429 || errorString.includes('429') || errorString.includes('RESOURCE_EXHAUSTED') || errorString.includes('quota')) {
      return "You have exceeded your Gemini API quota. Please check your plan and billing details at https://ai.google.dev/gemini-api/docs/rate-limits.";
    }
    return "Error generating draft. Please try again.";
  }
}
