import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TripDetails, QuotationItem } from '../types';

export const generateQuotationPDF = (details: TripDetails, items: QuotationItem[], agencySettings?: any) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129); // emerald-600
  doc.text(agencySettings?.agencyName || 'TravelAI Quotation', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  if (agencySettings?.email) doc.text(agencySettings.email, 14, 30);
  if (agencySettings?.phone) doc.text(agencySettings.phone, 14, 35);
  if (agencySettings?.website) doc.text(agencySettings.website, 14, 40);

  // Divider
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, 45, pageWidth - 14, 45);

  // Trip Info
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont('helvetica', 'bold');
  doc.text('Quotation Details', 14, 55);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Client: ${details.clientName}`, 14, 65);
  doc.text(`Trip: ${details.tripName}`, 14, 70);
  doc.text(`Pax: ${details.paxCount}`, 14, 75);
  doc.text(`Dates: ${details.startDate} to ${details.endDate}`, 14, 80);

  // Table
  const tableData = items.map(item => [
    item.segment,
    item.description,
    item.quantity.toString(),
    item.unitPrice.toLocaleString(),
    item.totalPrice.toLocaleString()
  ]);

  autoTable(doc, {
    startY: 90,
    head: [['Segment', 'Description', 'Qty', 'Unit Price', 'Total']],
    body: tableData,
    headStyles: { fillColor: [16, 185, 129] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { top: 90 },
  });

  // Total
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  const total = items.reduce((sum, i) => sum + i.totalPrice, 0);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Amount: ${total.toLocaleString()}`, pageWidth - 14, finalY + 15, { align: 'right' });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Generated by TravelAI Assistant', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`Quotation_${details.clientName.replace(/\s+/g, '_')}.pdf`);
};
